/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Represents the type of button event */
export const enum ButtonType {
  Left = 'Left',
  Right = 'Right',
  Middle = 'Middle',
  Unknown = 'Unknown',
}
/** Represents keyboard keys */
export const enum KeyCode {
  Alt = 'Alt',
  AltGr = 'AltGr',
  Backspace = 'Backspace',
  CapsLock = 'CapsLock',
  ControlLeft = 'ControlLeft',
  ControlRight = 'ControlRight',
  Delete = 'Delete',
  DownArrow = 'DownArrow',
  End = 'End',
  Escape = 'Escape',
  F1 = 'F1',
  F2 = 'F2',
  F3 = 'F3',
  F4 = 'F4',
  F5 = 'F5',
  F6 = 'F6',
  F7 = 'F7',
  F8 = 'F8',
  F9 = 'F9',
  F10 = 'F10',
  F11 = 'F11',
  F12 = 'F12',
  Home = 'Home',
  LeftArrow = 'LeftArrow',
  MetaLeft = 'MetaLeft',
  MetaRight = 'MetaRight',
  NumLock = 'NumLock',
  PageDown = 'PageDown',
  PageUp = 'PageUp',
  Return = 'Return',
  RightArrow = 'RightArrow',
  ShiftLeft = 'ShiftLeft',
  ShiftRight = 'ShiftRight',
  Space = 'Space',
  Tab = 'Tab',
  UpArrow = 'UpArrow',
  PrintScreen = 'PrintScreen',
  ScrollLock = 'ScrollLock',
  Pause = 'Pause',
  Insert = 'Insert',
  BackQuote = 'BackQuote',
  Num1 = 'Num1',
  Num2 = 'Num2',
  Num3 = 'Num3',
  Num4 = 'Num4',
  Num5 = 'Num5',
  Num6 = 'Num6',
  Num7 = 'Num7',
  Num8 = 'Num8',
  Num9 = 'Num9',
  Num0 = 'Num0',
  Minus = 'Minus',
  Equal = 'Equal',
  KeyQ = 'KeyQ',
  KeyW = 'KeyW',
  KeyE = 'KeyE',
  KeyR = 'KeyR',
  KeyT = 'KeyT',
  KeyY = 'KeyY',
  KeyU = 'KeyU',
  KeyI = 'KeyI',
  KeyO = 'KeyO',
  KeyP = 'KeyP',
  LeftBracket = 'LeftBracket',
  RightBracket = 'RightBracket',
  KeyA = 'KeyA',
  KeyS = 'KeyS',
  KeyD = 'KeyD',
  KeyF = 'KeyF',
  KeyG = 'KeyG',
  KeyH = 'KeyH',
  KeyJ = 'KeyJ',
  KeyK = 'KeyK',
  KeyL = 'KeyL',
  SemiColon = 'SemiColon',
  Quote = 'Quote',
  BackSlash = 'BackSlash',
  IntlBackslash = 'IntlBackslash',
  KeyZ = 'KeyZ',
  KeyX = 'KeyX',
  KeyC = 'KeyC',
  KeyV = 'KeyV',
  KeyB = 'KeyB',
  KeyN = 'KeyN',
  KeyM = 'KeyM',
  Comma = 'Comma',
  Dot = 'Dot',
  Slash = 'Slash',
  KpReturn = 'KpReturn',
  KpMinus = 'KpMinus',
  KpPlus = 'KpPlus',
  KpMultiply = 'KpMultiply',
  KpDivide = 'KpDivide',
  Kp0 = 'Kp0',
  Kp1 = 'Kp1',
  Kp2 = 'Kp2',
  Kp3 = 'Kp3',
  Kp4 = 'Kp4',
  Kp5 = 'Kp5',
  Kp6 = 'Kp6',
  Kp7 = 'Kp7',
  Kp8 = 'Kp8',
  Kp9 = 'Kp9',
  KpDelete = 'KpDelete',
  Function = 'Function',
  Unknown = 'Unknown',
}
/** Represents the type of event */
export const enum EventTypeValue {
  KeyPress = 'KeyPress',
  KeyRelease = 'KeyRelease',
  MouseMove = 'MouseMove',
  ButtonPress = 'ButtonPress',
  ButtonRelease = 'ButtonRelease',
  Wheel = 'Wheel',
}
/** Represents a key press event */
export interface KeyPressEvent {
  key: KeyCode
}
/** Represents a key release event */
export interface KeyReleaseEvent {
  key: KeyCode
}
/** Represents a mouse move event */
export interface MouseMoveEvent {
  x: number
  y: number
}
/** Represents a button press event */
export interface ButtonPressEvent {
  button: ButtonType
}
/** Represents a button release event */
export interface ButtonReleaseEvent {
  button: ButtonType
}
/** Represents a wheel event */
export interface WheelEvent {
  deltaX: number
  deltaY: number
}
/** Represents an input event */
export interface InputEvent {
  /** The type of event */
  eventType: EventTypeValue
  /** Key press data (only present for KeyPress events) */
  keyPress?: KeyPressEvent
  /** Key release data (only present for KeyRelease events) */
  keyRelease?: KeyReleaseEvent
  /** Mouse move data (only present for MouseMove events) */
  mouseMove?: MouseMoveEvent
  /** Button press data (only present for ButtonPress events) */
  buttonPress?: ButtonPressEvent
  /** Button release data (only present for ButtonRelease events) */
  buttonRelease?: ButtonReleaseEvent
  /** Wheel data (only present for Wheel events) */
  wheel?: WheelEvent
  /** Optional name of window (platform-dependent) */
  name?: string
  /** Timestamp of the event */
  time: number
}
/** Display size information */
export interface DisplaySize {
  width: number
  height: number
}
/** Get the size of the main display */
export declare function getDisplaySize(): DisplaySize
/** Start listening for input events */
export declare function startListener(callback: (event: InputEvent) => void): void
/** Simulate an input event */
export declare function simulateEvent(event: InputEvent): void
